server {
    listen 80;
    server_name localhost assados-vaguinho.grasciano.com.br;

    root /usr/share/nginx/html;
    index index.html;

    # Cabeçalhos de Segurança
    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-Content-Type-Options "nosniff";
    add_header Referrer-Policy "strict-origin-when-cross-origin";

    # NUNCA fazer cache do index.html ou Service Worker (Força busca da versão nova ao abrir)
    location ~* (index\.html|sw\.js|registerSW\.js|workbox-.*\.js|manifest\.webmanifest)$ {
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
        expires -1;
    }

    # SPA Routing (React/Vite fallback)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Static assets cache com hash no nome
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|avif|webp)$ {
        expires 7d;
        add_header Cache-Control "public, no-transform";
    }
}
